Repository KiteretsuSaiSama/Daihyakka-DSA, pull requests merged in 2021-10, with the labels that each got.

#15 Created Moore's Voting Algorithm #14
  Moore's Voting Algorithm
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#16 Add Seperate Chaining
  SeperateChaining.c
Labels: hacktoberfest-accepted, hacktoberfest

#18 Create KadanesAlgorithm.py
  KadanesAlgorithm.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#19 Create Kadane's Algo.cpp
  Kadane's Algo.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#26 Largest Sum Contiguous Subarray Kadane's Algo in Java
  Bubble.cpp
  Kadane's Algo.java
  MergeSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest
